# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('caseid', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('casename', models.CharField(max_length=100, verbose_name='用例名称')),
                ('identity', models.CharField(max_length=50, verbose_name='用户身份')),
                ('url', models.CharField(max_length=250, verbose_name='访问路径')),
                ('method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('header', models.CharField(max_length=200, verbose_name='请求头')),
                ('params', models.TextField(verbose_name='请求参数')),
                ('body', models.TextField(verbose_name='请求体内容')),
                ('exceptres', models.CharField(max_length=250, verbose_name='期望结果')),
                ('result', models.CharField(max_length=250, verbose_name='执行结果')),
                ('belong', models.CharField(max_length=50, verbose_name='所属模块')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('upwd', models.CharField(max_length=30, verbose_name='密码')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('uemail', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
