# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='result',
            field=models.TextField(verbose_name='执行结果'),
        ),
    ]
