# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20190705_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcase',
            fields=[
                ('webcaseid', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('webcase_models', models.CharField(max_length=250, verbose_name='所属模块')),
                ('webidentity', models.CharField(max_length=50, verbose_name='用户身份')),
                ('webcasename', models.CharField(max_length=250, verbose_name='测试用例名称')),
                ('webteststep', models.TextField(verbose_name='测试步骤')),
                ('webexceptres', models.CharField(max_length=250, verbose_name='期望结果')),
                ('webresult', models.TextField(verbose_name='执行结果')),
                ('webcreat_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
