# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_webcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webcase',
        ),
    ]
