# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_webcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcase',
            name='webbelong',
            field=models.CharField(default=datetime.datetime(2019, 7, 18, 10, 15, 9, 126383, tzinfo=utc), max_length=250, verbose_name='父模块'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcase',
            name='webfunpoint',
            field=models.CharField(default=datetime.datetime(2019, 7, 18, 10, 15, 13, 483347, tzinfo=utc), max_length=250, verbose_name='功能点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcase',
            name='webpremise',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='前提条件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webexceptres',
            field=models.CharField(max_length=500, verbose_name='期望结果'),
        ),
    ]
