# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20190718_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='webidentity',
            field=models.CharField(blank=True, max_length=50, verbose_name='用户身份'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webresult',
            field=models.TextField(blank=True, verbose_name='执行结果'),
        ),
    ]
