# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-09 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20190718_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autocase',
            fields=[
                ('autoid', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('autobelong', models.CharField(max_length=250, verbose_name='父模块')),
                ('autoidentity', models.CharField(blank=True, max_length=50, verbose_name='用户身份')),
                ('autoname', models.CharField(max_length=250, verbose_name='测试用例名称')),
                ('autostep', models.TextField(verbose_name='测试步骤')),
                ('autodataready', models.CharField(max_length=500, verbose_name='数据准备')),
                ('autoexceptres', models.CharField(max_length=500, verbose_name='期望结果')),
                ('autoresult', models.TextField(blank=True, verbose_name='执行结果')),
                ('autocreat_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
