# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_autocase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processapi',
            fields=[
                ('caseid', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('casename', models.CharField(max_length=100, verbose_name='用例名称')),
                ('identity', models.CharField(max_length=50, verbose_name='用户身份')),
                ('url', models.CharField(max_length=250, verbose_name='访问路径')),
                ('method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('header', models.CharField(max_length=200, verbose_name='请求头')),
                ('params', models.TextField(verbose_name='请求参数')),
                ('body', models.TextField(verbose_name='请求体内容')),
                ('exceptres', models.CharField(max_length=250, verbose_name='期望结果')),
                ('result', models.TextField(verbose_name='执行结果')),
                ('belong', models.CharField(max_length=50, verbose_name='所属模块')),
                ('isprocess', models.CharField(max_length=20, verbose_name='是否有依赖')),
                ('depend_id', models.CharField(max_length=20, verbose_name='依赖的caseID')),
                ('depend_key', models.CharField(max_length=100, verbose_name='依赖的key')),
                ('replace_key', models.CharField(max_length=100, verbose_name='替换的key')),
                ('replace_position', models.CharField(default='params', max_length=50, verbose_name='替换的内容区域')),
                ('order_no', models.CharField(max_length=20, verbose_name='排序号')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='belong_system',
            field=models.CharField(default='', max_length=50, verbose_name='所属系统'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='isprocess',
            field=models.CharField(default='', max_length=50, verbose_name='是否为流程测试'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
