# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20190829_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='belong_system',
            field=models.CharField(max_length=60, verbose_name='所属系统'),
        ),
    ]
