# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-29 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20190829_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='belong_system',
        ),
    ]
