# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_remove_case_belong_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='system',
            field=models.CharField(default='', max_length=50, verbose_name='所属系统'),
            preserve_default=False,
        ),
    ]
