# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-05 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_case_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='processapi',
            name='system',
            field=models.CharField(default='', max_length=50, verbose_name='所属系统'),
            preserve_default=False,
        ),
    ]
