# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_processapi_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='dataType',
            field=models.CharField(default='', max_length=150, verbose_name='数据类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='isMust',
            field=models.CharField(default='', max_length=50, verbose_name='是否必须'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='parameterName',
            field=models.CharField(default='', max_length=250, verbose_name='参数名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='parameterThat',
            field=models.CharField(default='', max_length=250, verbose_name='参数说明'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='requestType',
            field=models.CharField(default='', max_length=50, verbose_name='请求类型'),
            preserve_default=False,
        ),
    ]
