# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_auto_20190924_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocase',
            name='sortid',
            field=models.IntegerField(default=1, verbose_name='排序号'),
            preserve_default=False,
        ),
    ]
