# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_case_sortid'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcase',
            name='system',
            field=models.CharField(default='erms', max_length=50, verbose_name='所属系统'),
            preserve_default=False,
        ),
    ]
