# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_webcase_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='processapi',
            name='sortid',
            field=models.IntegerField(default=1, verbose_name='排序号'),
            preserve_default=False,
        ),
    ]
