# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_processapi_sortid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processapi',
            name='depend_key',
            field=models.CharField(max_length=500, verbose_name='依赖的key'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='replace_key',
            field=models.CharField(max_length=500, verbose_name='替换的key'),
        ),
    ]
