# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_processapi_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='duration',
            field=models.FloatField(default=1, verbose_name='响应时长'),
            preserve_default=False,
        ),
    ]
