"""
Django settings for Testapi project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e45c&ss7jk3=+(rp!k3lm$_ogolyvko!rd0=1bkmm8-=-82#9e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'Api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Testapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Testapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Testapi',
        'USER':'root',
        'PASSWORD':'123456',
        'HOST':'47.98.56.102',#47.98.56.102
        'PORT':'3306',
        "CONN_MAX_AGE":9

    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# 设置语言
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

#设置时区
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

#设置字符集
DEFAULT_CHARSET = "utf-8"

#国际化
USE_I18N = True

#相同内容被不同时区地区的用户访问时，是否以不同格式内容展示(例如时间，日期，数字)
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#制定静态文件的访问路径
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR,'static'),)
# STATIC_ROOT = '/Users/zhuzhanhao/Testapi/Api/static/'

#指定静态文件的存储路径
# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static')
# ]

# 设置sessionid存活时间为30分钟
# SESSION_COOKIE_AGE = 60*30*10
#设置关闭浏览器时则清空对应的session空间
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOG_FILE = "./../logs/debug.log"


LOGGING = {
    # version, 只能为1
    'version': 1,
    # True 表示禁用loggers
    'disable_existing_loggers': True,

    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    # 【格式化】- [可以配置多种样式分别命名，根据需要选择保存的格式]
    'formatters': {
        'simple': {
            'format': '[%(levelname)s] %(module)s : %(message)s'
        },
        'verbose': {
            'format': '[%(asctime)s] [%(levelname)s] [%(funcName)s] : %(message)s'
        }
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',#输出到Stream。通常用来打印到标准输出。
            'formatter': 'verbose'
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': os.path.join(BASE_DIR, "logs",'debug.log'),#日志输出文件
            'mode': 'a',
        },
        #'file': {
            #'level': 'DEBUG',
            #'class': 'logging.handlers.RotatingFileHandler',#自动按大小切分的log文件
            #'class': 'logging.FileHandler',
            #'formatter': 'verbose',
            #'filename': LOG_FILE,
            #'filename': os.path.join(BASE_DIR, "logs",'debug.log'),#日志输出文件
            #'maxBytes': 5 * 1024 * 1024,
            #'backupCount': 5,#备份份数
        #},
        # 'mail_admins': {
        #     'level': 'ERROR',
        #     'class': 'django.utils.log.AdminEmailHandler',
        #     'filters': ['require_debug_false']# 仅当 DEBUG = False 时才发送邮件
        # }
    },
    #logging管理器
    'loggers': {
        # '': {
        #     'handlers': ['file', 'console'],
        #     'level': 'INFO',
        #     'propagate': True,
        #     },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # 'django.request': {
        #     'handlers': ['mail_admins', 'console'],
        #     'level': 'ERROR',
        #     'propagate': True,
        # },
    }
}